//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCommerse.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string productName { get; set; }
        public string descProduct { get; set; }
        public int idBrand { get; set; }
        public int idCategory { get; set; }
        public Nullable<decimal> priceProduct { get; set; }
        public Nullable<int> quantityProduct { get; set; }
        public string status { get; set; }
        public Nullable<int> idRating { get; set; }
        public Nullable<int> idImage { get; set; }
    }
}
